config/routes.rb
Food::Application.routes.draw do

    resources :daily_intakes

    root to: 'static_pages#index'

    scope '/:locale' do
        scope '/food/item' do
            # food item
            match '/:item_id', to: 'food_item#show', as: 'fetch_food_item', via: :get
            match '/add_to_basket/:item_id', to: 'user_session#add_items_to_basket', via: [:post, :get], as: 'add_item_to_basket'
            match '/delete_from_basket/:item_id', to: 'user_session#delete_item_from_basket', via: [:post, :get], as: 'delete_item_from_basket'
        end

        match '/delete_items_from_basket/', to: 'user_session#delete_all_items', via: [:post, :get], as: 'bulk_delete_basket'
        # search
        match '/search/:query', to: 'food_item#search', as: 'search_db', via: :get
        match '/compare', to: 'food_item#compare', as: 'compare_items', via: :get
    end

    match '/change/url/to/:locale(/:query)', to: 'application#change_lang', via: [:get, :post], as: 'change_lang'

    # user session
    get 'users/new', as: 'user_new'
    match '/user_session/change_user_settings', to: 'user_session#change_user_settings', via: [:post]
    get ':controller(/:action(/:id(.:format)))'

    # admin login actions
    scope '/admin' do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users, only: [:index, :new, :create, :destroy]
        get '/' => 'sessions#new', :as => 'login'
        get '/logout' => 'sessions#destroy', :as => 'logout'
        get '/signup' => 'users#new', :as => 'signup'
        get '/dashboard' => 'admin_dashboard#index', as: 'dashboard'
        get '/delete/user/:user_id' => 'users#destroy', as: 'user_delete'
        get '/search/cache/clear' => 'food_item#clear_search_cache', as: 'clear_search_cache'
    end
end

app/models/user_session.rb
##
# user_session.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

require_dependency 'user_session/user_basket'
require_dependency 'user_session/user_settings'

class UserSession
    def initialize(session)
        @session                 = session
        @session[:item_basket]   ||= [] # init session item_basket
        @session[:user_settings] ||= {
            weight: 80,
            height: 180,
            age:    21
        }
    end

    include UserBasket
    include UserSettings
end

app/models/user_session/user_basket.rb
##
# user_basket.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

module UserBasket
    include FoodApisModule

    def delete_all_items
        @session[:item_basket] = []
    end

    ##
    # checks if element is already in the user list
    # if not it adds the item to the item_basket
    def add_item_to_basket(item_id)
        @session[:item_basket] << item_id unless @session[:item_basket].include? item_id
    end

    def delete_item_from_basket(basket_idx)
        @session[:item_basket].delete_at(basket_idx.to_i)
    end

    def add_items_to_basket(items)
        @session[:item_basket] = items
    end

    def fetch_user_items
        basket = FoodItem.fetch_local_items @session[:item_basket]
        return nil if basket.nil?
        basket
    end
end

app/models/user_session/user_settings.rb
##
# user_settings.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

module UserSettings
    def fetch_user_settings
        @session[:user_settings]
    end

    def change_user_settings(params)
        @session[:user_settings] = {
            weight: params[:user_settings][:user_settings_weight],
            height: params[:user_settings][:user_settings_height],
            age:    params[:user_settings][:user_settings_age],
            sex:    params[:user_settings][:user_settings_sex]
        }
    end
end

app/controllers/user_session_controller.rb
##
# user_session_controller.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

require 'awesome_print'
class UserSessionController < ApplicationController
    def change_user_settings
        user_session.change_user_settings params
        respond_to do |format|
            format.html { redirect_to :back }
            format.js
        end
    end

    def delete_item_from_basket
        user_session.delete_item_from_basket params[:item_id]
        respond_to do |format|
            format.html { redirect_to :back }
            format.js { render 'user_session/add_items_to_basket' }
        end
    end

    def delete_all_items
        user_session.delete_all_items
        respond_to do |format|
            format.html { redirect_to :back }
            format.js { render 'user_session/add_items_to_basket' }
        end
    end

    def add_items_to_basket
        user_session.add_item_to_basket params[:item_id]
        respond_to do |format|
            format.html { redirect_to :back }
            format.js
        end
    end
end

app/views/user_session/_add_items_to_basket.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	      Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<h1>Elements in Comparison-Basket </h1>
<nav id="secondary">
  <%= link_to "delete all items", bulk_delete_basket_path, :class => 'icon-remove', :remote => true %>
  <%= link_to "compare items", compare_items_path, :class => 'icon-line-chart' %>
</nav>

<ul id="food-item-list">
  <% if user_session.fetch_user_items.class == Array %>
      <% user_session.fetch_user_items.each_with_index do |item, idx| %>
          <li data-item-idx="<%= item['_id'] %>">
            <span class="header">
              <span class="name"><%= item['name'] %></span>
              <span class="info">
                <%= link_to '', fetch_food_item_path(item['_id']), :class => 'icon-pie-chart'%>
                <%= link_to '', delete_item_from_basket_path(idx), :class => 'icon-remove', :remote => true %>
              </span>
            </span>
            <span class="content clearfix">
            <% item['nutritions'].each do |key, value| %>
              <% if print_nutrition_element? key %>
                <span class="ingredient">
                    <span class="highlighted"><%= I18n.t key %></span>
                    <span class="simple"><%= value %></span>
                </span>
              <% end %>
            <% end %>
            </span>


          </li>
      <% end %>
  <% end %>
</ul>

app/views/user_session/_change_user_settings.js.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

$('body').append('<%= j render('user_session/change_user_settings') %>');

app/views/user_session/add_items_to_basket.js.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

$('#user-basket').html('<%= j render ('user_session/add_items_to_basket') %>');

app/views/user_session/change_user_settings.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>
<h1>User Settings</h1>
<%= form_for 'user_settings', remote: true, url: { controller: 'user_session', action: 'change_user_settings' } do |f| %>
    <%= f.label :user_settings_weight %><br>
    <%= f.text_field :user_settings_weight, :placeholder => 'weight', :value => @user_session.fetch_user_settings[:weight] %>
    <%= f.label :user_settings_age %><br>
    <%= f.text_field :user_settings_age, :placeholder => 'age', :value => @user_session.fetch_user_settings[:age] %>
    <%= f.label :user_settings_height %><br>
    <%= f.text_field :user_settings_height, :placeholder => 'height', :value => @user_session.fetch_user_settings[:height] %>


    <%= f.label :user_settings_sex %><br>
    <div class="radio-toolbar">
      <%= f.radio_button :user_settings_sex, 'man' %>
      <%= f.label :user_settings_sex, t("man"), :value => 'man' %>
      <%= f.radio_button :user_settings_sex, 'woman', :checked => true %>
      <%= f.label :user_settings_sex, t("woman"), :value => 'woman' %>
    </div>
    <%= f.submit "save changes" %>

<% end %>
<h1> Select Language </h1>
<ul>
  <li>
    <%= link_to "french", change_lang_path(:locale => "fr") %>
  </li>
  <li>
    <%= link_to "spanish", change_lang_path(:locale => "es") %>
  </li>
  <li>
    <%= link_to "german", change_lang_path(:locale => "de") %>
  </li>
  <li>
    <%= link_to "chinese", change_lang_path(:locale => "zh-CHT") %>
  </li>
  <li>
    <%= link_to "hindu", change_lang_path(:locale => "hi") %>
  </li>
  <li>
    <%= link_to "russian", change_lang_path(:locale => "ru") %>
  </li>
  <li>
    <%= link_to "arabic", change_lang_path(:locale => "ar") %>
  </li>
</ul>