config/routes.rb
Food::Application.routes.draw do

    resources :daily_intakes

    root to: 'static_pages#index'

    scope '/:locale' do
        scope '/food/item' do
            # food item
            match '/:item_id', to: 'food_item#show', as: 'fetch_food_item', via: :get
            match '/add_to_basket/:item_id', to: 'user_session#add_items_to_basket', via: [:post, :get], as: 'add_item_to_basket'
            match '/delete_from_basket/:item_id', to: 'user_session#delete_item_from_basket', via: [:post, :get], as: 'delete_item_from_basket'
        end

        match '/delete_items_from_basket/', to: 'user_session#delete_all_items', via: [:post, :get], as: 'bulk_delete_basket'
        # search
        match '/search/:query', to: 'food_item#search', as: 'search_db', via: :get
        match '/compare', to: 'food_item#compare', as: 'compare_items', via: :get
    end

    match '/change/url/to/:locale(/:query)', to: 'application#change_lang', via: [:get, :post], as: 'change_lang'

    # user session
    get 'users/new', as: 'user_new'
    match '/user_session/change_user_settings', to: 'user_session#change_user_settings', via: [:post]
    get ':controller(/:action(/:id(.:format)))'

    # admin login actions
    scope '/admin' do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users, only: [:index, :new, :create, :destroy]
        get '/' => 'sessions#new', :as => 'login'
        get '/logout' => 'sessions#destroy', :as => 'logout'
        get '/signup' => 'users#new', :as => 'signup'
        get '/dashboard' => 'admin_dashboard#index', as: 'dashboard'
        get '/delete/user/:user_id' => 'users#destroy', as: 'user_delete'
        get '/search/cache/clear' => 'food_item#clear_search_cache', as: 'clear_search_cache'
    end
end

app/views/layouts/_partials/_header.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<div id="header-wrp" class="clearfix">
  <div class="display-table">
    <div class="display-table-cell logo-small-wrp">
      <%= link_to root_path do %>
          <%= image_tag 'logo_white.svg', :height => 60 %>
      <% end %>
    </div>
    <div class="display-table-cell search-form-wrp responsive-hide">
      <%= form_for('search/results/', :remote => true, :url => url_for(:controller => 'food_item', :action => 'redirect_to_index'), :html => { :id => 'header-search' }, method: "get") do %>
          <div class="col span_10">
            <%= text_field_tag :query %>
          </div>
          <div class="col span_2">
            <%= submit_tag("Search") %>
          </div>
      <% end %>
    </div>
    <div class="display-table-cell icon-wrp">
      <ul class="menu" id="main-menu">
        <li><a href="#user-basket" class="icon-basket active"></a></li>
        <li><a href="#user-settings" class="icon-cog"></a></li>
        <% if logged_in? %>
            <li><%= link_to '', dashboard_path, :class => 'icon-dashboard' %></li>
            <li><%= link_to '', logout_path, :class => 'icon-leave' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_partials/_sidebar.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<%= form_for('search/results/', :html => { :class => 'responsive-show clearfix search' }, :url => url_for(:controller => 'food_item', :action => 'redirect_to_index'), method: "get") do |f| %>
    <!--<form id="search" class="container row">-->
    <%= text_field_tag :query %>
    <button class="button-search icon-search" type="submit">
      <span>Search</span>
    </button>
<% end %>
<div id="user-basket" class="active">
  <%= render :template => 'user_session/_add_items_to_basket' %>
</div>
<div id="user-settings">
  <%= render :template => 'user_session/change_user_settings' %>
</div>