config/routes.rb
Food::Application.routes.draw do

    resources :daily_intakes

    root to: 'static_pages#index'

    scope '/:locale' do
        scope '/food/item' do
            # food item
            match '/:item_id', to: 'food_item#show', as: 'fetch_food_item', via: :get
            match '/add_to_basket/:item_id', to: 'user_session#add_items_to_basket', via: [:post, :get], as: 'add_item_to_basket'
            match '/delete_from_basket/:item_id', to: 'user_session#delete_item_from_basket', via: [:post, :get], as: 'delete_item_from_basket'
        end

        match '/delete_items_from_basket/', to: 'user_session#delete_all_items', via: [:post, :get], as: 'bulk_delete_basket'
        # search
        match '/search/:query', to: 'food_item#search', as: 'search_db', via: :get
        match '/compare', to: 'food_item#compare', as: 'compare_items', via: :get
    end

    match '/change/url/to/:locale(/:query)', to: 'application#change_lang', via: [:get, :post], as: 'change_lang'

    # user session
    get 'users/new', as: 'user_new'
    match '/user_session/change_user_settings', to: 'user_session#change_user_settings', via: [:post]
    get ':controller(/:action(/:id(.:format)))'

    # admin login actions
    scope '/admin' do
        resources :sessions, only: [:create, :destroy, :new]
        resources :users, only: [:index, :new, :create, :destroy]
        get '/' => 'sessions#new', :as => 'login'
        get '/logout' => 'sessions#destroy', :as => 'logout'
        get '/signup' => 'users#new', :as => 'signup'
        get '/dashboard' => 'admin_dashboard#index', as: 'dashboard'
        get '/delete/user/:user_id' => 'users#destroy', as: 'user_delete'
        get '/search/cache/clear' => 'food_item#clear_search_cache', as: 'clear_search_cache'
    end
end

app/models/daily_intake.rb
##
# daily_intake.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

class DailyIntake
    include Mongoid::Document
    field :key, type: String
    field :value, type: Float
    field :unit, type: String
    field :category, type: String

    validates :key, :value, :unit, :category, presence: true
    validates :key, uniqueness: true
    validates :category, inclusion: { in:  %w( selection general vitamin mineral ) }
    validates :unit, inclusion: { in: %w( g mg kcal l ) }

    def self.find_element(key)
        DailyIntake.where(key: key).first
    end
end

app/controllers/daily_intakes_controller.rb
##
# daily_intakes_controller.rb
#
# university:  University of Applied Sciences Salzburg
# studie:      MultiMediaTechnology
# usage:	    Multimediaprojekt 2a (MMP2a)
# author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
#              - Franziska Oberhauser

class DailyIntakesController < ApplicationController
    before_filter :require_login
    before_action :set_daily_intake, only: [:show, :edit, :update, :destroy]

    # GET /daily_intakes
    # GET /daily_intakes.json
    def index
        @daily_intakes = DailyIntake.all
    end

    # GET /daily_intakes/1
    # GET /daily_intakes/1.json
    def show
    end

    # GET /daily_intakes/new
    def new
        @daily_intake = DailyIntake.new
    end

    # GET /daily_intakes/1/edit
    def edit
    end

    # POST /daily_intakes
    # POST /daily_intakes.json
    def create
        @daily_intake = DailyIntake.new(daily_intake_params)

        respond_to do |format|
            if @daily_intake.save
                format.html { redirect_to @daily_intake, notice: 'Daily intake was successfully created.' }
                format.json { render action: 'show', status: :created, location: @daily_intake }
            else
                format.html { render action: 'new' }
                format.json { render json: @daily_intake.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /daily_intakes/1
    # PATCH/PUT /daily_intakes/1.json
    def update
        respond_to do |format|
            if @daily_intake.update(daily_intake_params)
                format.html { redirect_to @daily_intake, notice: 'Daily intake was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @daily_intake.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /daily_intakes/1
    # DELETE /daily_intakes/1.json
    def destroy
        @daily_intake.destroy
        respond_to do |format|
            format.html { redirect_to daily_intakes_url }
            format.json { head :no_content }
        end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_daily_intake
        @daily_intake = DailyIntake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_intake_params
        params.require(:daily_intake).permit(:key, :value, :unit, :category)
    end

    private :set_daily_intake, :daily_intake_params
end

app/views/daily_intakes/_form.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>
<%= form_for(@daily_intake) do |f| %>
    <% if @daily_intake.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@daily_intake.errors.count, "error") %> prohibited this daily_intake from being saved:</h2>

          <ul>
            <% @daily_intake.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :key %>
      <br>
      <%= f.text_field :key %>
    </div>
    <div class="field">
      <%= f.label :value %>
      <br>
      <%= f.text_field :value %>
    </div>
    <div class="field">
      <%= f.label :unit %>
      <br>
      <%= f.select :unit, %w( g mg kcal l ) %>
    </div>
    <div class="field">
      <%= f.label :category %>
      <br>
      <%= f.select :category, %w( selection general vitamin mineral ) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/daily_intakes/edit.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<h1>Editing daily_intake</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_intake %> |
<%= link_to 'Back', daily_intakes_path %>

app/views/daily_intakes/index.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<h1>Listing daily_intakes</h1>

<table>
  <thead>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th>Unit</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @daily_intakes.each do |daily_intake| %>
      <tr>
        <td><%= daily_intake.key %></td>
        <td><%= daily_intake.value %></td>
        <td><%= daily_intake.unit %></td>
        <td><%= daily_intake.category %></td>
        <td><%= link_to 'Show', daily_intake %></td>
        <td><%= link_to 'Edit', edit_daily_intake_path(daily_intake) %></td>
        <td><%= link_to 'Destroy', daily_intake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily intake', new_daily_intake_path %>

app/views/daily_intakes/new.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<h1>New daily_intake</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_intakes_path %>

app/views/daily_intakes/show.html.erb
<%
   # university:  University of Applied Sciences Salzburg
   # studie:      MultiMediaTechnology
   # usage:	    Multimediaprojekt 2a (MMP2a)
   # author:      - Thomas Mayrhofer (thomas@mayrhofer.at)
   #              - Franziska Oberhauser
%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @daily_intake.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @daily_intake.value %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @daily_intake.unit %>
</p>

<p>
  <strong>Category:</strong>
  <%= @daily_intake.category %>
</p>

<%= link_to 'Edit', edit_daily_intake_path(@daily_intake) %> |
<%= link_to 'Back', daily_intakes_path %>